[package]
name = "tui"
version = "0.1.0"
edition = "2024"
description = "TUI for the lichen installer"
repository = "https://github.com/AerynOS/lichen-installer"
authors = ["Bryan Hyland <bryan.hyland32@gmail.com"]

[[bin]]
name = "lichen_tui"
path = "src/main.rs"

[dependencies]
installer = { path = "../crates/installer" }
protocols = { path = "../crates/protocols" }
chrono-tz.workspace = true
color-eyre.workspace = true
kdl.workspace = true
nix = { workspace = true, features = ["user"] }
ratatui = "0.30.2"
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true, features = ["transport"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
