[workspace]
members = [
    "lichen_cli",
]
default-members = [
    "lichen_cli"
]
resolver = "2"


[workspace.dependencies]

[workspace.lints.rust]
rust_2018_idioms = { level = "warn", priority = -1 }
semicolon_in_expressions_from_macros = "warn"
unused_import_braces = "warn"
unused_qualifications = "warn"
