[package]
name = "cli"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/AerynOS/lichen-installer"

[[bin]]
name = "lichen_cli"
path = "src/main.rs"

[build-dependencies]
installer = { path = "../crates/installer" }

[dependencies]
protocols = { path = "../crates/protocols" }
#tonic = { workspace = true }
installer = { path = "../crates/installer" }
chrono.workspace = true
chrono-tz.workspace = true
cliclack.workspace = true
color-eyre = { workspace = true, features = ["issue-url"] }
console.workspace = true
kdl.workspace = true
sha-crypt.workspace = true
#serde.workspace = true
#serde_json.workspace = true
tracing.workspace = true
tracing-error.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tokio = { workspace = true, features = ["full"] }
async-trait.workspace = true
clap = { version = "4.6.4", features = ["derive"] }

[lints]
workspace = true
